pygments: true
permalink: /post/:title
markdown: kramdown
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git']
paginate: 4
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
